[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
authors = ["Kyle L. Davis <aceofspades5757.github@gmail.com>"]

[dependencies]
# CLI
clap = { version = "4.0.29", features = ["derive", "help"] }
